### ISSUE TITLE
API not reflecting on dashboard

### ISSUE THREAD

**Issue by alihaidermalik04** [Treblle/treblle-python#1]
I have configured treblle with my local environment below are my settings
```
if TREBLLE_ENABLED:
    INSTALLED_APPS += ["treblle"]
    MIDDLEWARE += ["treblle.middleware.TreblleMiddleware"]

    TREBLLE_INFO = {
        "api_key": TREBLLE_API_KEY,
        "project_id": TREBLLE_PROJECT_ID,
        "hidden_keys": ["token", "otp", "password", "mobile_account_no"],
    }
```
when i hit the API I do get this log from treblle
```
backend_1           | treblle Trebble response code 200
backend_1           | treblle Trebble response content b'{"status":true,"message":"Treblle got it"}'
```

but nothing reflect on my dashboard (sometimes it doesn't)
![image](https://user-images.githubusercontent.com/84305913/164404293-b98bfba5-0ead-4a9b-afa8-aabac19b7688.png)

Project settings are below
![MS Paint _ Microsoft Paint Online](https://user-images.githubusercontent.com/84305913/164404678-4af3f6fb-747c-4b15-9eb1-be34403eeb9e.png)

**Comment by cindreta** [comment]
Had nothing to do with the SDK. Managed to figure it all out!
